### ISSUE TITLE
Changelog bot extraction of labels fails if no labels

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/changelog-bot-action#9]
Was introduced in the 0.1.0 update.

**Comment by SeanTAllen** [comment]
@jemc i'm not great with some of the stuff i cribbed from your code.

can you tell me what i broke with:

https://github.com/ponylang/changelog-bot-action/commit/f2b96476341425619175892f56c0afdfcd2b019f#diff-b958f585a04af5ee2087610ea7180f34

I wanted to remove the "to upper" portion and thought i did but apparently i did more than that.

**Comment by jemc** [comment]
Adding ` || true` after the `grep` should fix it.

This script is using `set -e` so that errors won't go unnoticed. But when commands are piped together, only the exit status of the final command matters.

The `grep` command obviously fails when none of the tags are present to find, which is causing the script to crash in that case. But it seems that `awk` was always returning a success exit status even when the `grep` failed, so that explains why we didn't see that issue when the `awk` was the final command.

The `true` command returns success unconditionally and prints nothing. So, adding ` || true` has the desired effect of explicitly ignoring/consuming the error from `grep`, while printing nothing into the output stream of the subshell, so that the `CHANGELOG_TYPES` variable will be an empty string in that case like we want.

I have tested that this works as desired using this basic mockup script:

```sh
set -e

str="No labels to notice here"

echo "extracting..."
things=$(
  echo "${str}" |
  grep -o -E 'added|changed' || true
)

echo "done extracting!"

for thing in $things; do
  echo "thing: '${thing}'"
done

echo "done printing!"
```

**Comment by SeanTAllen** [comment]
Nice will test now. Thanks, @jemc.
